NUM_ROWS = 4
NUM_COLS = 4
NUM_TILES = NUM_COLS*NUM_ROWS

UP = 'Up'
RIGHT = 'Right'
DOWN = 'Down'
LEFT = 'Left'
ALL_MOVES = [UP,RIGHT,DOWN,LEFT]

ROW_1_INDECIES = [0,  1,  2,  3]
ROW_2_INDECIES = [4,  5,  6,  7]
ROW_3_INDECIES = [8,  9,  10, 11]
ROW_4_INDECIES = [12, 13, 14, 15]

COL_1_INDECIES = [ROW_1_INDECIES[0], ROW_2_INDECIES[0], ROW_3_INDECIES[0], ROW_4_INDECIES[0]]
COL_2_INDECIES = [ROW_1_INDECIES[1], ROW_2_INDECIES[1], ROW_3_INDECIES[1], ROW_4_INDECIES[1]]
COL_3_INDECIES = [ROW_1_INDECIES[2], ROW_2_INDECIES[2], ROW_3_INDECIES[2], ROW_4_INDECIES[2]]
COL_4_INDECIES = [ROW_1_INDECIES[3], ROW_2_INDECIES[3], ROW_3_INDECIES[3], ROW_4_INDECIES[3]]

ROWS = [ROW_1_INDECIES,ROW_2_INDECIES,ROW_3_INDECIES,ROW_4_INDECIES]
COLS = [COL_1_INDECIES,COL_2_INDECIES,COL_3_INDECIES,COL_4_INDECIES]

UP_ORDER = []
UP_ORDER.extend(ROW_1_INDECIES)
UP_ORDER.extend(ROW_2_INDECIES)
UP_ORDER.extend(ROW_3_INDECIES)
UP_ORDER.extend(ROW_4_INDECIES)

DOWN_ORDER = []
DOWN_ORDER.extend(ROW_4_INDECIES)
DOWN_ORDER.extend(ROW_3_INDECIES)
DOWN_ORDER.extend(ROW_2_INDECIES)
DOWN_ORDER.extend(ROW_1_INDECIES)

LEFT_ORDER = []
LEFT_ORDER.extend(COL_1_INDECIES)
LEFT_ORDER.extend(COL_2_INDECIES)
LEFT_ORDER.extend(COL_3_INDECIES)
LEFT_ORDER.extend(COL_4_INDECIES)

RIGHT_ORDER = []
RIGHT_ORDER.extend(COL_4_INDECIES)
RIGHT_ORDER.extend(COL_3_INDECIES)
RIGHT_ORDER.extend(COL_2_INDECIES)
RIGHT_ORDER.extend(COL_1_INDECIES)

STACK_OPTIONS = [1,1,1,1,2,2,2,2,3,3,3,3]
